name: Validate Pull Request

on:
  pull_request:
    branches:
      - "**" # Trigger on all branches for PRs

jobs:
  validate:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create .env file with secret values
      - name: Set up environment variables
        run: echo 'PATH_TO_WALLET="test/testWallet.json"' > .env

      # Build the project
      - name: Build project
        run: npm run build

      # Run unit tests
      - name: Run unit tests
        run: npm run test:unit

      # Check if version has been bumped
      - name: Check version bump
        id: version-check
        run: |
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version)
          CURRENT_VERSION=$(jq -r .version package.json)
          if [ "$PREVIOUS_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Version has not been bumped! Please update the version in package.json."
            exit 1
          else
            echo "Version bumped successfully."
          fi
