name: Publish to npm

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Authenticate with npm
      - name: Authenticate with npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Publish package
      - name: Publish package
        run: npm publish --access public
